spring.application.name=transportHub

# MongoDB configuration
spring.data.mongodb.host=${MONGODB_HOST:localhost}
spring.data.mongodb.port=${MONGODB_PORT:27017}
spring.data.mongodb.database=${MONGODB_DB:transportHubDB}
spring.data.mongodb.authentication-database=${MONGODB_AUTH_DB:transportHubDB}
spring.data.mongodb.username=${MONGODB_USERNAME:transporthub}
spring.data.mongodb.password=${MONGODB_PASSWORD:transporthub}

# Spring security configuration
spring.security.user.name=${SPRING_SECURITY_USER_NAME:admin}
spring.security.user.password=${SPRING_SECURITY_USER_PASSWORD:password}

# Custom property for BusLine JSON source
busline.json.url=http://datos.santander.es/api/datos/lineas_bus.json
busstop.json.url=https://datos.santander.es/api/rest/datasets/paradas_bus.json