spring.application.name=transportHub

# MongoDB configuration
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/transportHub}
spring.data.mongodb.database=transportHub
spring.data.mongodb.host=transport-hub-db
spring.data.mongodb.port=27017
spring.data.mongodb.authentication-database=admin
spring.data.mongodb.username=${MONGODB_USERNAME:transporthub}
spring.data.mongodb.password=${MONGODB_PASSWORD:transporthub}

# Spring security configuration
spring.security.user.name=${SPRING_SECURITY_USER_NAME:admin}
spring.security.user.password=${SPRING_SECURITY_USER_PASSWORD:password}

# Custom property for BusLine JSON source
busline.json.url=http://datos.santander.es/api/datos/lineas_bus.json